<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tmpl</string>
		<string>inc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|li|form|dl)\b.*?&gt;|&lt;!--(?!.*--\s*&gt;)|^&lt;!--\ \#tminclude\ (?&gt;.*?--&gt;)$|&lt;\?(?:php)?.*\b(if|for(each)?|while)\b.+:|\{\{?(if|foreach|capture|literal|foreach|php|section|strip)|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/))))</string>
	<key>foldingStopMarker</key>
	<string>(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|li|form|dl)&gt;|^(?!.*?&lt;!--).*?--\s*&gt;|^&lt;!--\ end\ tminclude\ --&gt;$|&lt;\?(?:php)?.*\bend(if|for(each)?|while)\b|\{\{?/(if|foreach|capture|literal|foreach|php|section|strip)|^[^{]*\})</string>
	<key>keyEquivalent</key>
	<string>^~H</string>
	<key>name</key>
	<string>HTML Templates</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;)(TMPL_COMMENT)(&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html.html-template</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.html.html-template</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html.html-template</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)(TMPL_COMMENT)(&gt;)</string>
			<key>name</key>
			<string>meta.tag.block.any.html.html-template</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&lt;TMPL_.*?&gt;</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.*?</string>
					<key>name</key>
					<string>comment.block.html</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#tmpl-tags</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>expression-perl-method</key>
		<dict>
			<key>match</key>
			<string>\b[a-zA-Z0-0-_]+(?=\(.*\))</string>
			<key>name</key>
			<string>entity.name.function.perl.expression.html.html-template</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\s+\d</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html.html-template</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html.html-template</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.html</string>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html.html-template</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html.html-template</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.html</string>
		</dict>
		<key>tag-perl-attribute</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z:-]{1,})(?==)</string>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
		</dict>
		<key>tag-perl-expression</key>
		<dict>
			<key>begin</key>
			<string>\[%</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.perl.expression.start.html.html-template</string>
				</dict>
			</dict>
			<key>end</key>
			<string>%\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.perl.expression.end.html.html-template</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-perl-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression-perl-method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
			</array>
		</dict>
		<key>tag-perl-keyword</key>
		<dict>
			<key>match</key>
			<string>(\s+(eq|ne|or|and|not)|=~|&amp;&amp;|==|\|\||!~|&lt;=?|[^-]&gt;=?)</string>
			<key>name</key>
			<string>keyword.perl.expression.html.html-template</string>
		</dict>
		<key>tag-perl-options</key>
		<dict>
			<key>match</key>
			<string>\b([A-Z_]{1,})</string>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
		</dict>
		<key>tmpl-tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-perl-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-perl-options</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-perl-expression</string>
				</dict>
			</array>
		</dict>
		<key>tmpl-tags</key>
		<dict>
			<key>begin</key>
			<string>(&lt;[/~]?)(TMPL_(?i:[a-zA-Z]+)\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.begin.html.html-template</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.html.html-template</string>
				</dict>
			</dict>
			<key>end</key>
			<string>([~]?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.end.html.html-template</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.block.any.html.html-template</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tmpl-tag-stuff</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.html-template</string>
</dict>
</plist>
